apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
namePrefix: azureprep-

resources:
  - ../../base

labels:
  app.kubernetes.io/name: azureprep
  app.kubernetes.io/part-of: certprep

patches:
  # Web deployment patches
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: azureprep-web
      - op: replace
        path: /spec/template/metadata/labels/app
        value: azureprep-web
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: azureprep:latest
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: postgresql://azureprep:azurepreppass@azureprep-db:5432/azureprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: azureprep2024
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: Azure Prep

  # Web service patches
  - target:
      kind: Service
      name: web
    patch: |
      - op: replace
        path: /spec/selector/app
        value: azureprep-web

  # Ingress patches
  - target:
      kind: Ingress
      name: ingress
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: azureprep.dev.jgcloud.es
      - op: replace
        path: /spec/tls/0/secretName
        value: azureprep-tls
      - op: replace
        path: /spec/rules/0/host
        value: azureprep.dev.jgcloud.es

  # DB deployment patches
  - target:
      kind: Deployment
      name: db
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: azureprep-db
      - op: replace
        path: /spec/template/metadata/labels/app
        value: azureprep-db
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: azureprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: azurepreppass
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: azureprep

  # DB service patches
  - target:
      kind: Service
      name: db
    patch: |
      - op: replace
        path: /spec/selector/app
        value: azureprep-db
