apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
namePrefix: gcpprep-

resources:
  - ../../base

commonLabels:
  app.kubernetes.io/name: gcpprep
  app.kubernetes.io/part-of: certprep

patches:
  # Web deployment patches
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: gcpprep-web
      - op: replace
        path: /spec/template/metadata/labels/app
        value: gcpprep-web
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: gcpprep:latest
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: postgresql://gcpprep:gcppreppass@gcpprep-db:5432/gcpprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: gcpprep2024
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: GCP Prep

  # Web service patches
  - target:
      kind: Service
      name: web
    patch: |
      - op: replace
        path: /spec/selector/app
        value: gcpprep-web

  # Ingress patches
  - target:
      kind: Ingress
      name: ingress
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: gcpprep.dev.jgcloud.es
      - op: replace
        path: /spec/tls/0/secretName
        value: gcpprep-tls
      - op: replace
        path: /spec/rules/0/host
        value: gcpprep.dev.jgcloud.es

  # DB deployment patches
  - target:
      kind: Deployment
      name: db
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: gcpprep-db
      - op: replace
        path: /spec/template/metadata/labels/app
        value: gcpprep-db
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: gcpprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: gcppreppass
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: gcpprep

  # DB service patches
  - target:
      kind: Service
      name: db
    patch: |
      - op: replace
        path: /spec/selector/app
        value: gcpprep-db
