apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
namePrefix: itfundprep-

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: itfundprep-web
      - op: replace
        path: /spec/template/metadata/labels/app
        value: itfundprep-web
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: itfundprep:latest
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: postgresql://itfundprep:itfundpreppass@itfundprep-db:5432/itfundprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: itfundprep2024
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: IT Fundamentals Prep
  - target:
      kind: Service
      name: web
    patch: |
      - op: replace
        path: /spec/selector/app
        value: itfundprep-web
  - target:
      kind: Ingress
      name: ingress
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: itfundprep.dev.jgcloud.es
      - op: replace
        path: /spec/tls/0/secretName
        value: itfundprep-tls
      - op: replace
        path: /spec/rules/0/host
        value: itfundprep.dev.jgcloud.es
  - target:
      kind: Deployment
      name: db
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: itfundprep-db
      - op: replace
        path: /spec/template/metadata/labels/app
        value: itfundprep-db
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: itfundprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: itfundpreppass
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: itfundprep
  - target:
      kind: Service
      name: db
    patch: |
      - op: replace
        path: /spec/selector/app
        value: itfundprep-db
