---
k3s_version: "v1.31.4+k3s1"
k3s_install_url: "https://get.k3s.io"
k3s_config_dir: "/etc/rancher/k3s"
k3s_server_args: "--disable traefik --write-kubeconfig-mode 644"
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
