apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
namePrefix: linuxprep-

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: linuxprep-web
      - op: replace
        path: /spec/template/metadata/labels/app
        value: linuxprep-web
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: linuxprep:latest
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: postgresql://linuxprep:linuxpreppass@linuxprep-db:5432/linuxprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: linuxprep2024
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: Linux Prep
  - target:
      kind: Service
      name: web
    patch: |
      - op: replace
        path: /spec/selector/app
        value: linuxprep-web
  - target:
      kind: Ingress
      name: ingress
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: linuxprep.dev.jgcloud.es
      - op: replace
        path: /spec/tls/0/secretName
        value: linuxprep-tls
      - op: replace
        path: /spec/rules/0/host
        value: linuxprep.dev.jgcloud.es
  - target:
      kind: Deployment
      name: db
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: linuxprep-db
      - op: replace
        path: /spec/template/metadata/labels/app
        value: linuxprep-db
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: linuxprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: linuxpreppass
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: linuxprep
  - target:
      kind: Service
      name: db
    patch: |
      - op: replace
        path: /spec/selector/app
        value: linuxprep-db
