apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
namePrefix: comptiprep-

resources:
  - ../../base

labels:
  app.kubernetes.io/name: comptiprep
  app.kubernetes.io/part-of: certprep

patches:
  # Web deployment patches
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: comptiprep-web
      - op: replace
        path: /spec/template/metadata/labels/app
        value: comptiprep-web
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: comptiprep:latest
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: postgresql://comptiprep:comptipreppass@comptiprep-db:5432/comptiprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: comptiprep2024
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: CompTIA Prep

  # Web service patches
  - target:
      kind: Service
      name: web
    patch: |
      - op: replace
        path: /spec/selector/app
        value: comptiprep-web

  # Ingress patches
  - target:
      kind: Ingress
      name: ingress
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: comptiprep.dev.jgcloud.es
      - op: replace
        path: /spec/tls/0/secretName
        value: comptiprep-tls
      - op: replace
        path: /spec/rules/0/host
        value: comptiprep.dev.jgcloud.es

  # DB deployment patches
  - target:
      kind: Deployment
      name: db
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: comptiprep-db
      - op: replace
        path: /spec/template/metadata/labels/app
        value: comptiprep-db
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: comptiprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: comptipreppass
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: comptiprep

  # DB service patches
  - target:
      kind: Service
      name: db
    patch: |
      - op: replace
        path: /spec/selector/app
        value: comptiprep-db
