apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
namePrefix: cloudprep-

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: cloudprep-web
      - op: replace
        path: /spec/template/metadata/labels/app
        value: cloudprep-web
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cloudprep:latest
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: postgresql://cloudprep:cloudpreppass@cloudprep-db:5432/cloudprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: cloudprep2024
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: Cloud Prep
  - target:
      kind: Service
      name: web
    patch: |
      - op: replace
        path: /spec/selector/app
        value: cloudprep-web
  - target:
      kind: Ingress
      name: ingress
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: cloudprep.dev.jgcloud.es
      - op: replace
        path: /spec/tls/0/secretName
        value: cloudprep-tls
      - op: replace
        path: /spec/rules/0/host
        value: cloudprep.dev.jgcloud.es
  - target:
      kind: Deployment
      name: db
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/app
        value: cloudprep-db
      - op: replace
        path: /spec/template/metadata/labels/app
        value: cloudprep-db
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: cloudprep
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: cloudpreppass
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: cloudprep
  - target:
      kind: Service
      name: db
    patch: |
      - op: replace
        path: /spec/selector/app
        value: cloudprep-db
